// import React from 'react';
// import {
//   Box,
//   Typography,
//   Paper,
//   TextField,
//   Button,
//   List,
//   ListItem,
//   ListItemIcon,
//   ListItemText,
//   CircularProgress,
//   InputAdornment,
//   Divider,
//   Tooltip,
//   IconButton,
//   Grid
// } from '@mui/material';
// import CheckCircleIcon from '@mui/icons-material/CheckCircle';
// import InfoIcon from '@mui/icons-material/Info';
// import LocalAtmIcon from '@mui/icons-material/LocalAtm';

// function Stake({ stakeAmount, setStakeAmount, handleStakeReputation, isLoading }) {
//   return (
//     <Box p={2}>
//       <Typography variant="h5" gutterBottom>
//         Reputation Staking
//       </Typography>
//       <Paper elevation={3} sx={{ p: 3, maxWidth: 600, mx: 'auto' }}>
//         <Typography variant="body1" gutterBottom>
//           Stake your ICP to boost your reputation score and unlock exclusive benefits.
//         </Typography>
//         <TextField
//           label="Amount to Stake (ICP)"
//           type="number"
//           value={stakeAmount}
//           onChange={(e) => setStakeAmount(Number(e.target.value))}
//           fullWidth
//           variant="outlined"
//           margin="normal"
//           InputProps={{
//             endAdornment: <InputAdornment position="end">ICP</InputAdornment>
//           }}
//         />
//         <Divider sx={{ my: 2 }} />
//         <Typography variant="subtitle1" gutterBottom>
//           Staking Benefits
//         </Typography>
//         <List>
//           <ListItem>
//             <ListItemIcon>
//               <CheckCircleIcon color="success" />
//             </ListItemIcon>
//             <ListItemText primary="Amplify your reputation score" />
//           </ListItem>
//           <ListItem>
//             <ListItemIcon>
//               <CheckCircleIcon color="success" />
//             </ListItemIcon>
//             <ListItemText primary="Access exclusive dApp features" />
//           </ListItem>
//           <ListItem>
//             <ListItemIcon>
//               <CheckCircleIcon color="success" />
//             </ListItemIcon>
//             <ListItemText primary="Earn additional reputation yields" />
//           </ListItem>
//         </List>
//         <Grid container spacing={2} sx={{ mt: 2 }}>
//           <Grid item xs={6}>
//             <Button
//               variant="contained"
//               color="primary"
//               fullWidth
//               onClick={handleStakeReputation}
//               disabled={stakeAmount <= 0 || isLoading}
//             >
//               {isLoading ? (
//                 <CircularProgress size={20} color="inherit" />
//               ) : (
//                 'Stake Now'
//               )}
//             </Button>
//           </Grid>
//           <Grid item xs={6} container justifyContent="center" alignItems="center">
//             <Tooltip title="Staking boosts your reputation and unlocks exclusive opportunities.">
//               <IconButton>
//                 <InfoIcon />
//               </IconButton>
//             </Tooltip>
//           </Grid>
//         </Grid>
//       </Paper>
//     </Box>
//   );
// }

// export default Stake;

import React from 'react';
import { 
  Box, Typography, Paper, TextField, Button, 
  List, ListItem, ListItemIcon, ListItemText, 
  CircularProgress, InputAdornment, Divider, Tooltip,
  IconButton, Grid
} from '@mui/material';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import InfoIcon from '@mui/icons-material/Info';
import LocalAtmIcon from '@mui/icons-material/LocalAtm';

function Stake({ stakeAmount, setStakeAmount, handleStakeReputation, isLoading }) {
  return (
    <Box p={2}>
      <Typography variant="h5" gutterBottom>
        Boost Your AI Reputation Score
      </Typography>
      <Paper elevation={3} sx={{ p: 3, maxWidth: 600, mx: 'auto' }}>
        <Typography variant="body1" gutterBottom>
          Stake your ICP to further boost your reputation score generated by our Rust‑powered ML model.
        </Typography>
        <TextField
          label="Amount to Stake (ICP)"
          type="number"
          value={stakeAmount}
          onChange={(e) => setStakeAmount(Number(e.target.value))}
          fullWidth
          variant="outlined"
          margin="normal"
          InputProps={{
            endAdornment: <InputAdornment position="end">ICP</InputAdornment>
          }}
        />
        <Divider sx={{ my: 2 }} />
        <Typography variant="subtitle1" gutterBottom>
          Staking Benefits
        </Typography>
        <List>
          <ListItem>
            <ListItemIcon>
              <CheckCircleIcon color="success" />
            </ListItemIcon>
            <ListItemText primary="Amplify your AI-driven reputation score" />
          </ListItem>
          <ListItem>
            <ListItemIcon>
              <CheckCircleIcon color="success" />
            </ListItemIcon>
            <ListItemText primary="Access exclusive trust features" />
          </ListItem>
          <ListItem>
            <ListItemIcon>
              <CheckCircleIcon color="success" />
            </ListItemIcon>
            <ListItemText primary="Earn additional reputation yields" />
          </ListItem>
        </List>
        <Grid container spacing={2} sx={{ mt: 2 }}>
          <Grid item xs={6}>
            <Button
              variant="contained"
              color="primary"
              fullWidth
              onClick={handleStakeReputation}
              disabled={stakeAmount <= 0 || isLoading}
            >
              {isLoading ? (
                <CircularProgress size={20} color="inherit" />
              ) : (
                'Stake Now'
              )}
            </Button>
          </Grid>
          <Grid item xs={6} container justifyContent="center" alignItems="center">
            <Tooltip title="Staking boosts your reputation and unlocks exclusive trust features.">
              <IconButton>
                <InfoIcon />
              </IconButton>
            </Tooltip>
          </Grid>
        </Grid>
      </Paper>
    </Box>
  );
}

export default Stake;